feat: normalize: clean normalization of text input
mongulu-cm/tchoung-te pull request #49
Opened 2022-09-22 20:16 UTC by KameniAlexNea

2022-09-22 20:24 UTC, KameniAlexNea commented
J'ai sauvegardé sous le format zip à cause de la limite d'espaces dans un commit (taille du fichier).

À la fin, je vais voir comment réduire tout ça.

2022-09-23 12:21 UTC, billmetangmo commented
Bien reçu, je vais regarder ça

2022-10-27 14:34 UTC, KameniAlexNea commented
Sinon, je pense avoir fait le tour, si tout est bon pour vous aussi, @billmetangmo peut merger

2022-10-28 16:35 UTC, billmetangmo commented
oki les chagements sont validés @KameniAlexNea .
J'ai rajouté ton fichier 4.xxxx dans un dossier experiment et j'ai ajouté tes functions de normalisation filter-cameroon.ipynb. 
J'ai aussi supprimé ton fichier zip aussi , il est pas nécessaire d'après ton commentaire.

2022-10-28 16:42 UTC, KameniAlexNea commented
J'ai l'impression que tu n'as pas fait de merge de ma branche

2022-10-29 07:54 UTC, billmetangmo commented
Yes t'as raison. Je suis revenu à l'état précédent.
En fait les commits de main que j'ai rajouté se trouvent au-dessus des tiens dans ton historique. 
Du coup on aura un commit de plus qui sera un commit de merge avec résolution du conflit.

Ce qu'il faudrait faire pour y rémédier c'est que les commits tirés depuis master soient au-dessous des tiens.
Comme si tu avais fait refait ta base à partir de main. C'est un rebase.
`
## etape 1: reset ta branche sur ton commit
git checkout alex 
git reset --hard 8b60776e711b512f0ec32679221ed666deffd66b

## étape 2: mettre à jour main
git checkout main
git pull --rebase origin main

## étape 3: rebase alex sur main
git checkout alex
git rebase master
`

2022-10-29 08:18 UTC, billmetangmo requested changes
- [ ] Créer un dossier experiments dans etl pour y mettre le fichier 4.Process_data.ipynb étant donné que les bouts de code importants seront rajoutés dans filter-cameroon.ipynb . C'est pour garder le fichier néanmoins. On utilisera désormais ce dossier experiments pour faire des premiers tests en dehors du code même filter-cameroon. T'en penses koi ?

- [ ] Sinon, on pourrait supprimer le fichier etl/ref-rna-real-mars-2022-enriched-not-qualified-process.zip . Je pense d'après ton commentaire précédent qu'il n'est plus nécessaire

2022-10-29 08:18 UTC, billmetangmo commented on etl/filter-cameroon.ipynb
> +    "def normalize(df):\n",
J'ai introduit une fonction normalize en utilisant les pipelines. Tu pourras reporter dans cette fonction, le code te permettant te modifier de supprimer les guillemets sur objet, titre car ici on n'a pas encore les libellés d'objet social.

2022-10-29 08:18 UTC, billmetangmo commented on etl/filter-cameroon.ipynb
> +    "def format_libelle_for_gogocarto(df):\n",
C'est ici qu'il faudra rajouter aussi la supression des guillemets pour les colonnes objets libellés 1 & 2

2022-10-30 22:46 UTC, KameniAlexNea commented on etl/filter-cameroon.ipynb
> +    "def normalize(df):\n",
Désolé, je ne suis pas sûr de comprendre la fin

2022-10-30 22:47 UTC, KameniAlexNea commented on etl/filter-cameroon.ipynb
> +    "def normalize(df):\n",
C'est une bonne idée d'avoir un dossier spécial pour l'ensemble du code juste.

2022-10-31 06:43 UTC, KameniAlexNea commented
Stp @billmetangmo tu peux vérifier si ce que j'ai fait est bien dans la direction attendue ? On n'a pas encore pu discuter du prochain point

2022-11-02 09:10 UTC, billmetangmo commented on etl/filter-cameroon.ipynb
> +    "def normalize(df):\n",
En fait, je disais qu'il faudrait rajouter ton code qui permet de supprimer les guillemets à l'intérieur de la fonction normalize ici:

![image](https://user-images.githubusercontent.com/25366207/199449574-d874c796-176c-49f3-ad55-60ab2205a722.png)

Tu comprends mieux ?

2022-11-02 09:12 UTC, billmetangmo commented on etl/filter-cameroon.ipynb
> +    "def format_libelle_for_gogocarto(df):\n",
Ici il faut utiliser toujours ta même fonction sui supprime les guillemets mais sur les champs libellés:

![image](https://user-images.githubusercontent.com/25366207/199450230-85528dcb-b179-4cab-bfa3-5823dc4e52d1.png)

2022-11-02 11:41 UTC, billmetangmo commented
> Stp @billmetangmo tu peux vérifier si ce que j'ai fait est bien dans la direction attendue ? On n'a pas encore pu discuter du prochain point

Oui  @KameniAlexNea  c'est dans la bonne direction. T'as fait 70% du boulot. Il reste plus qu'à:

- [ ] Rajouter ton code de supression des guillements comme décrit [ici](https://github.com/mongulu-cm/tchoung-te/pull/49#discussion_r1011414949) et [là](https://github.com/mongulu-cm/tchoung-te/pull/49#discussion_r1011419773)

- [ ] L'historique n'est pas toujours bon. Mais c'est ma faute, j'ai oublié de te dire qu'il fallait que tu supprimes tous les commits que tu avais pris depuis main avant de rebase. 

**En fait, il faudrait quitter de ça**
![image](https://user-images.githubusercontent.com/25366207/199480918-1075b6df-4f3e-44f7-aeee-56601f5ebec4.png)

**Vers ceci**
![image](https://user-images.githubusercontent.com/25366207/199480748-7721ba8d-2d8e-48d2-bbc7-e38860a1ce27.png)

2022-11-07 04:29 UTC, KameniAlexNea commented
@billmetangmo c'est quand tu veux pour merger

2022-11-10 21:07 UTC, merged

2022-11-10 21:07 UTC, billmetangmo commented
oui @KameniAlexNea  tout est bon là. Je merge 👍🏾