Executer les notebook direct depuis l 'IDE (Ref #50)
mongulu-cm/tchoung-te pull request #54
Opened 2022-11-12 23:46 UTC by KameniAlexNea

2022-12-08 18:59 UTC, KameniAlexNea commented
Salut, 

Tous les checks sont bons, c'était un problème de formatage finalement réglé. J'ai attaché juste à l'issue #50 , Mais c'est bien lien à deux autres

@billmetangmo for review

2022-12-21 12:49 UTC, billmetangmo requested changes
Tout me semble bon niveau éxécution du code en faisant python3 enrich-cahe.py, python3 filter-cameroon.py cependant lorsqu'on éxécute le code depuis le scientific mode ( c'est à dire pas à pas). On se trouve avec l'erreur `TypeError: cannot pickle 'sqlite3.Connection' object` qui semble du au fait que l'object connection sqlite utilisé par request-cache n'est pas sérializable.

![Capture d’écran du 2022-12-21 13-46-54](https://user-images.githubusercontent.com/25366207/208908865-e788099d-92c6-4757-b7e8-a96b817de539.png)

Comme suggéré par chatGPT, une solution serait de passer le backend request-cache de sqlite vers un autre ( à voir dans la docuentation) mais cele signifierait perdre tout ce qui est actuellement dans sqlite. Ou peut-être y a-t-il un moyen de faire la conversion via request-cache? A checker.

2022-12-21 12:49 UTC, billmetangmo commented on etl/enrich-database.py
> +df['facebook_url'] = df.parallel_apply(lambda row: enrich("facebook.com",
I am not able to execute this cell using scientifc mode in Pycham. I got `TypeError: cannot pickle 'sqlite3.Connection' object`. Can you try it on your side ?

2022-12-21 12:49 UTC, billmetangmo commented on etl/filter-cameroon.py
> +df2 = df2.pipe(add_lat_lon) \
J'ai le même soucis ici `TypeError: cannot pickle 'sqlite3.Connection' object `. C'est visiblement lié à l'utilisation de requests-cache qui sauve les données dans sqlite ( cf https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.sqlite.html). Je pense que t'auras le même soucis chez toi. Tu peux regarder un fix possible ?

2023-02-04 15:04 UTC, billmetangmo commented on etl/enrich-database.py
> +df['facebook_url'] = df.parallel_apply(lambda row: enrich("facebook.com",
It was my pycharm ocnfiguration that was not good

2023-02-04 15:05 UTC, merged