Open ai for normalised address
mongulu-cm/tchoung-te pull request #73
Opened 2023-03-09 23:55 UTC by Joyce-Tchamdjou

Finished ?

2023-03-10 00:02 UTC, Joyce-Tchamdjou commented
Hola Bill 
Lorsque je clique je n'arrive pas à visualiser l'organisation. Tu sais c'est quoi le souci là s'il te plait?

2023-03-10 09:28 UTC, billmetangmo commented
> Hola Bill Lorsque je clique je n'arrive pas à visualiser l'organisation. Tu sais c'est quoi le souci là s'il te plait?

Je ne comprends pas . Tu veux dire quoi par visualiser l'organisation @Joyce-Tchamdjou  ?

2023-03-10 09:38 UTC, billmetangmo requested changes
Le gros du travail a été fait, il reste juste à passer de la modification de type_voie à clel de l'adresse complète.
**Ensuite, il faudra éxécuter le fichier filter-cameroon.py entièrement, tu l'as fait ?**

2023-03-10 09:38 UTC, billmetangmo commented on etl/filter-cameroon.py
>      df["adrs"] = df.apply(lambda row: expand_address(row["adrs"])[0], axis=1)
Il faut supprimer toutes les mentions à postal.expand donc celle de ta ligne 65.
Ensuite, il n'est pas nécessaire de modifier adrs_typevoie , la colonne importante c'est adrs. Il faut donc modifier la fonction `èxpand_adress` pour y mettre le code GPT3Prompt. Sachant que ce code doit modifier df["adrs"].

2023-03-14 22:55 UTC, billmetangmo commented
@Joyce-Tchamdjou non il faut plutôt modifier df["adrs"] au lieu de df["ads_voie"] . Je te fais un loom

2023-03-14 22:58 UTC, billmetangmo requested changes
Good mais il faut encore modifier df["adrs"]

2023-03-15 22:49 UTC, merged

2023-03-15 22:50 UTC, Joyce-Tchamdjou commented
Just in case
Je veux être sure avant de supprimer

2023-03-16 00:22 UTC, billmetangmo commented
Cool. Tu as fait un` python3 filter-cameroon.py` ? Sinon le fichier des associations est pas mis à jour et donc la modification est pas totalement pris en compte.